-- Resume Database Schema
-- PostgreSQL (Supabase Compatible)

-- =============================================
-- Livechat Messages
-- =============================================
CREATE TABLE IF NOT EXISTS livechat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- Guestbook Comments
-- =============================================
CREATE TABLE IF NOT EXISTS guestbook (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT DEFAULT NULL,
  comment TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE livechat ENABLE ROW LEVEL SECURITY;
ALTER TABLE guestbook ENABLE ROW LEVEL SECURITY;

-- Create Policies (Allow public read/write for guestbook/chat demo)
-- Note: Replace with specific auth roles if needed
CREATE POLICY "Public Read Livechat" ON livechat FOR SELECT USING (true);
CREATE POLICY "Public Insert Livechat" ON livechat FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Guestbook" ON guestbook FOR SELECT USING (true);
CREATE POLICY "Public Insert Guestbook" ON guestbook FOR INSERT WITH CHECK (true);
